# validates for new camera 02-12-2025 13:24
# flip true for naked board test 02-12-14:33

esphome:
  name: testcamera
  friendly_name: testCamera

esp32:
  board: esp32dev
  framework:
    type: arduino
 
# Enable logging
logger:
  level: VERBOSE
  tx_buffer_size: 256

# Enable Home Assistant API
api:
  encryption:
    key: "3zTlLiAas82U7CpNfQh47kZZ0mkVzs0FHF2DGiQiOxI="

ota:
  - platform: esphome
    password: "9bfbfd03dc060b07e6452b4f381bbce8"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Testcamera Fallback Hotspot"
    password: "TtecTt2VsF6C"

captive_portal:

# Display internal temperature of ESP32 processor
sensor:
  - platform: internal_temperature
    name: "ESP32 Camera Temperature"

esp32_camera:
  id: testCamera
  name: test-cam
  external_clock:
    pin: GPIO0
    frequency: 10MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  resolution: 800x600
  jpeg_quality: 10  # max. 63
  max_framerate: 1.0fps
  idle_framerate: 0.2fps
  vertical_flip: true
  horizontal_mirror: false
  brightness: 2 # -2 to 2
  contrast: 1 # -2 to 2
  special_effect: none
  # exposure settings
  aec_mode: auto
  aec2: false
  ae_level: 0
  aec_value: 300
  # gain settings
  agc_mode: auto
  agc_gain_ceiling: 2x
  agc_value: 0
  # white balance setting
  wb_mode: auto

output:
# white LED
  - platform: ledc
    channel: 2
    pin: GPIO4
    id: testCamLED
# red status light
  - platform: gpio
    pin:
      number: GPIO33
      inverted: True
    id: gpio_33
light:
  - platform: monochromatic
    output: testCamLED
    name: test-cam light
  - platform: binary
    output: gpio_33
    name: test-cam led
switch:
  - platform: restart
    name: test-cam restart
binary_sensor:
  - platform: status
    name: test-cam status
